twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: America/Vancouver
        format: Y-m-d g:i:s A
        interval_format: '%%d days'
    form_themes:
        - '@NinesUtil/form/bootstrap_5_horizontal_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        asset_prefix: '%env(default::string:ROUTE_BASE)%'
        nines_editor_config: js/editor-config.js
        text_service: '@Nines\UtilBundle\Services\Text'
        image_manager: '@Nines\MediaBundle\Service\ImageManager'
        linker: '@Nines\UtilBundle\Services\EntityLinker'
        piwik_enabled: '%dhil.piwik_enabled%'
        piwik_url: '%dhil.piwik_url%'
        piwik_siteid: '%dhil.piwik_siteid%'
        piwik_domain: '%dhil.piwik_domain%'
        date_format: Y-m-d
        git_repo: '%env(default::string:GIT_REPO)%'
        git_commit: '%env(default::string:GIT_COMMIT)%'
        git_commit_short: '%env(default::string:GIT_COMMIT_SHORT)%'
        git_branch: '%env(default::string:GIT_BRANCH)%'
        git_tag: '%env(default::string:GIT_TAG)%'

when@test:
    twig:
        strict_variables: true