<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220407175152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE archdeaconry CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE archive CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE book CHANGE title title LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE uniform_title uniform_title LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE variant_titles variant_titles LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\', CHANGE author author VARCHAR(160) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE imprint imprint LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE variant_imprint variant_imprint LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE estc estc VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE date date VARCHAR(12) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE physical_description physical_description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE notes notes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE county CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE diocese CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE format CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE holding CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE start_date start_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE end_date end_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE written_date written_date VARCHAR(60) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE notes notes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE injunction CHANGE title title LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE uniform_title uniform_title LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE variant_titles variant_titles LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\', CHANGE author author VARCHAR(160) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE imprint imprint LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE variant_imprint variant_imprint LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE date date VARCHAR(12) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE physical_description physical_description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE transcription transcription LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE estc estc VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE inventory CHANGE page_number page_number LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE transcription transcription LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE modifications modifications LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE start_date start_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE end_date end_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE written_date written_date VARCHAR(60) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE notes notes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE monarch CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE start_date start_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE end_date end_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nation CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_blog_page CHANGE title title VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE searchable searchable LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE excerpt excerpt LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE content content LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_blog_post CHANGE title title VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE searchable searchable LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE excerpt excerpt LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE content content LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_blog_post_category CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_blog_post_status CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_media_audio CHANGE entity entity VARCHAR(120) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE license license LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE original_name original_name VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE path path VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE mime_type mime_type VARCHAR(64) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_media_image CHANGE thumb_path thumb_path VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE entity entity VARCHAR(120) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE license license LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE original_name original_name VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE path path VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE mime_type mime_type VARCHAR(64) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_media_link CHANGE url url VARCHAR(500) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE text text VARCHAR(200) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE entity entity VARCHAR(120) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_media_pdf CHANGE thumb_path thumb_path VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE entity entity VARCHAR(120) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE license license LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE original_name original_name VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE path path VARCHAR(128) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE mime_type mime_type VARCHAR(64) NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE nines_user CHANGE email email VARCHAR(180) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE password password VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE fullname fullname VARCHAR(64) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE affiliation affiliation VARCHAR(64) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE parish CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE address address LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE province CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE source CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE call_number call_number VARCHAR(64) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE source_category CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE town CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE transact CHANGE location location VARCHAR(160) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE page page VARCHAR(24) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE transcription transcription LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE modern_transcription modern_transcription LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE public_notes public_notes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE start_date start_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE end_date end_date VARCHAR(10) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE written_date written_date VARCHAR(60) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE notes notes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE transaction_category CHANGE name name VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(200) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
    }
}
